---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: baselineweb
  labels:
    app: baselineweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baselineweb
  template:
    metadata:
      labels:
        app: baselineweb
    spec:
      containers:
      - name: baselineweb
        imagePullPolicy: Always
        image: gcr.io/github-actions-gke-385618/baseline:1.1.0
---
apiVersion: v1
kind: Service
metadata:
  name: baselineweb
spec:
  selector:
    app: baselineweb
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 8080
    port: 80
