---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baselineweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baselineweb
  template:
    metadata:
      labels:
        app: baselineweb
    spec:
      containers:
        - name: app
          image: gcr.io/github-actions-gke-385618/test2:1.1.0
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: baselineweb
spec:
  selector:
    app: baselineweb
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
