---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: baselineweb
  labels:
    app: baselineweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baselineweb
  template:
    metadata:
      labels:
        app: baselineweb
    spec:
      containers:
      - name: baselineweb
        imagePullPolicy: Never
        image: cloud.canister.io:5000/karthik21/base:Testing
        ports:
          - containerPort: 80
      # imagePullSecrets:
      # - name: regcred
