on:
 push:
  branches:
   - master

env:
  PROJECT_ID: ${{secrets.GKE_KS_PROJECTID}}
  GKE_CLUSTER: gke-github-actions
  GKE_ZONE: us-east4
  DEPLOYMENT_NAME: baselineweb

# Jobs needs to part..
jobs:
  setup-build-run-start:
    name: basewebpage
    runs-on: ubuntu-latest

    steps:
    #Checkout
      - name: Checkout Repository
        uses: actions/checkout@v3
    # GCP CLI
      - name: Setup Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          service_account_key: ${{secrets.GKE_KS_KEY}}
          project_id: ${{secrets.GKE_KS_PROJECTID}}
      - name: Configure Docker
        run: |-
          gcloud --quiet auth configure-docker
      - name: Build Docker Image
        run: |-
          docker build --tag "gcr.io/github-actions-gke-385618/baseline:1.1.0" .
      - name: Publish Docker Image to GCR
        run: |-
          docker push "gcr.io/github-actions-gke-385618/baseline:1.1.0"
  deploy:
    runs-on: ubuntu-latest
    needs: setup-build-run-start
    steps:
    #Checkout
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          service_account_key: ${{secrets.GKE_KS_KEY}}
          project_id: ${{secrets.GKE_KS_PROJECTID}}
      - name: "Auth to GCP exist env"
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{secrets.GKE_KS_KEY}}
      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v0
        with:
          install_components: 'gke-gcloud-auth-plugin'
      - name: "Connect to cluster"
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: gke-github-actions
          location: us-east4
          project_id: ${{secrets.GKE_KS_PROJECTID}}
          use_auth_provider: true
      - name: Configure Docker
        run: |-
          gcloud --quiet auth configure-docker
      - name: Get GKE Credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      - name: Deploy Image to GKE cluster
        run: |-
          kubectl apply -f k8-baselineweb.yml
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
