on:
 push:
  branches:
   - master

# Jobs needs to part
jobs:
  setup-build-run-start:
    name: basewebpage
    runs-on: ubuntu-latest

    steps:
    #Checkout
      - name: Checkout Repository
        uses: actions/checkout@v3
    #Build Docker:
      - name: docker build
        run: |
          docker build -t cloud.canister.io:5000/karthik21/base:Testing .
          docker images
    #Docker login:
      - name: docker login
        run: docker login --username=karthik21 --password=Dhivkk@#21 cloud.canister.io:5000
    #Docker Push:
      - name: docker Push
        run: docker push cloud.canister.io:5000/karthik21/base:Testing .
